<?php

namespace AppBundle\Repository;

/**
 * DirecteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DirecteurRepository extends \Doctrine\ORM\EntityRepository
{
}
