<?php

namespace AppBundle\Repository;

/**
 * SubventionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubventionRepository extends \Doctrine\ORM\EntityRepository
{
}
