# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        AppBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_USER: ROLE_USER

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        user:
          entity:
            class: AppBundle\Entity\User
            property: username

        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main_login:
                # Cette expression régulière permet de prendre /login (mais pas /login_check !)
          pattern:   ^/login$
          anonymous: true

        create:
                        # Cette expression régulière permet de prendre /login (mais pas /login_check !)
          pattern:   ^/create
          anonymous: true

        admin:
          pattern: ^/
          anonymous: false
          provider: user
          form_login:
            login_path: user_login
            check_path: user_login_check
            default_target_path: homepage
          logout:
            path: user_logout
            target: user_login

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
